// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8QjloulGeW8Djq9faMoo4wfmFNHamNQY',
    appId: '1:431276552444:web:4255ac78138b8e07b82779',
    messagingSenderId: '431276552444',
    projectId: 'rentalx-8d850',
    authDomain: 'rentalx-8d850.firebaseapp.com',
    storageBucket: 'rentalx-8d850.firebasestorage.app',
    measurementId: 'G-KGY6HVK3C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqN1EHy3GosgqFzanO7durneP5LSqkiDY',
    appId: '1:431276552444:android:aeb3c39d2f5d3dccb82779',
    messagingSenderId: '431276552444',
    projectId: 'rentalx-8d850',
    storageBucket: 'rentalx-8d850.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgR7Ly7_pDP4NCLJA2fsjM_wYi3F0R3e4',
    appId: '1:431276552444:ios:f6199e381a97accab82779',
    messagingSenderId: '431276552444',
    projectId: 'rentalx-8d850',
    storageBucket: 'rentalx-8d850.firebasestorage.app',
    iosClientId:
        '431276552444-or8s0njiq2i88bne7lsuf3tdj3nk0ijg.apps.googleusercontent.com',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgR7Ly7_pDP4NCLJA2fsjM_wYi3F0R3e4',
    appId: '1:431276552444:ios:f6199e381a97accab82779',
    messagingSenderId: '431276552444',
    projectId: 'rentalx-8d850',
    storageBucket: 'rentalx-8d850.firebasestorage.app',
    iosClientId:
        '431276552444-or8s0njiq2i88bne7lsuf3tdj3nk0ijg.apps.googleusercontent.com',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8QjloulGeW8Djq9faMoo4wfmFNHamNQY',
    appId: '1:431276552444:web:04628db41581e35ab82779',
    messagingSenderId: '431276552444',
    projectId: 'rentalx-8d850',
    authDomain: 'rentalx-8d850.firebaseapp.com',
    storageBucket: 'rentalx-8d850.firebasestorage.app',
    measurementId: 'G-ZZQQRWN0K2',
  );
}
